# Generated by Django 2.0.1 on 2019-07-10 13:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInWeekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='名称')),
                ('project_type', models.CharField(max_length=20, verbose_name='类型')),
                ('time_plan', models.CharField(max_length=20, verbose_name='项目周期')),
                ('describe', models.TextField(blank=True, max_length=500, null=True, verbose_name='项目描述')),
                ('status', models.CharField(max_length=20, verbose_name='项目状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '周报中的项目',
                'verbose_name_plural': '周报中的项目',
            },
        ),
        migrations.CreateModel(
            name='Weekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('occupation', models.CharField(max_length=20, verbose_name='职位')),
                ('group_leader', models.CharField(blank=True, max_length=20, null=True, verbose_name='组长')),
                ('plan', models.TextField(max_length=1000, verbose_name='任务计划')),
                ('completed', models.CharField(max_length=10, verbose_name='是否完成')),
                ('comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='管理员意见')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '周报',
                'verbose_name_plural': '周报',
            },
        ),
        migrations.AddField(
            model_name='projectinweekly',
            name='parentweekly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeklyprojects', to='weeklies.Weekly', verbose_name='周报'),
        ),
    ]
