# Generated by Django 2.0.1 on 2019-07-10 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weeklies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekly',
            name='comment',
        ),
        migrations.AlterField(
            model_name='projectinweekly',
            name='project_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='projectinweekly',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='projectinweekly',
            name='time_plan',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='项目周期'),
        ),
        migrations.AlterField(
            model_name='weekly',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weekly', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weekly',
            name='completed',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='是否完成'),
        ),
        migrations.AlterField(
            model_name='weekly',
            name='occupation',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='weekly',
            name='plan',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='任务计划'),
        ),
    ]
