# Generated by Django 2.0.1 on 2019-07-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklies', '0002_auto_20190710_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekly',
            name='last_revision',
            field=models.DateField(auto_now=True, verbose_name='上次修改时间'),
        ),
    ]
