# Generated by Django 2.0.1 on 2019-07-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklies', '0003_weekly_last_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekly',
            name='comment',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='管理员评论'),
        ),
    ]
