# Generated by Django 2.0.1 on 2019-07-10 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, '前端组'), (2, '后台组'), (3, '运维组'), (4, 'UI组'), (5, '产品经理组'), (6, '其他')], unique=True, verbose_name='名称')),
                ('img', models.ImageField(blank=True, null=True, upload_to='group_images/', verbose_name='组的封面')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '组',
                'verbose_name_plural': '组',
            },
        ),
    ]
