# Generated by Django 2.0.1 on 2019-07-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(choices=[('前端组', '前端组'), ('后台组', '后台组'), ('运维组', '运维组'), ('UI组', 'UI组'), ('产品经理组', '产品经理组'), ('其他组', '其他组')], max_length=15, unique=True, verbose_name='名称'),
        ),
    ]
