# Generated by Django 2.0.1 on 2019-07-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('前端', '前端'), ('后台', '后台'), ('运维', '运维'), ('UI', 'UI'), ('产品经理', '产品经理'), ('其他', '其他')], max_length=15, null=True, verbose_name='职位'),
        ),
    ]
