# Generated by Django 2.0.1 on 2019-07-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190710_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.IntegerField(blank=True, choices=[(1, '前端'), (2, '后台'), (3, '运维'), (4, 'UI'), (5, '产品经理'), (6, '其他')], null=True, verbose_name='职位'),
        ),
    ]
