# Generated by Django 2.0.1 on 2019-07-10 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190710_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='my_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupmembers', to='groups.Group', verbose_name='所属组'),
        ),
    ]
