# Generated by Django 2.0.1 on 2019-07-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190710_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_unencoded',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='管理员可见密码'),
        ),
    ]
