# Generated by Django 2.0.1 on 2019-07-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_password_unencoded'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_admitted',
            field=models.BooleanField(default=False, verbose_name='是否申请成功'),
        ),
    ]
