# Generated by Django 2.0.1 on 2019-07-10 13:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='名称')),
                ('project_type', models.CharField(max_length=20, verbose_name='类型')),
                ('group_leader', models.CharField(max_length=15, verbose_name='负责人')),
                ('describe', models.TextField(blank=True, max_length=1000, null=True, verbose_name='项目描述')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='开始日期')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('occupation', models.CharField(max_length=20, null=True, verbose_name='职位')),
                ('task', models.CharField(max_length=100, verbose_name='任务')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectmembers', to='teamprojects.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目成员',
                'verbose_name_plural': '项目成员',
            },
        ),
    ]
