# Generated by Django 2.0.1 on 2019-07-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamprojects', '0002_auto_20190710_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='group_leader',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='类型'),
        ),
    ]
